#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright © 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Author: Tencent AI Arena Authors

Drone Delivery PPO configuration.
智运无人机 PPO 配置。
"""


class Config:

    # Map geometry / 地图几何
    MAP_SIZE = 128
    MAX_COORD = MAP_SIZE - 1
    MAX_CHEBYSHEV_DIST = MAP_SIZE - 1
    LOCAL_MAP_SIDE = 21
    LOCAL_MAP_RADIUS = LOCAL_MAP_SIDE // 2
    LOCAL_MAP_CHANNELS = 3

    # Feature dimensions / 特征维度
    HERO_STATE_DIM = 4
    STATION_FEAT_DIM = 7
    STATION_TOPK = 3
    STATION_DIM = STATION_FEAT_DIM * STATION_TOPK
    CHARGER_DIM = 7
    NPC_DIM = 7
    LEGAL_ACT_DIM = 8
    INDICATOR_DIM = 3
    WAREHOUSE_DIM = 5
    MODE_DIM = 4
    TARGET_DIM = 5
    LOCAL_MAP_DIM = LOCAL_MAP_SIDE * LOCAL_MAP_SIDE * LOCAL_MAP_CHANNELS

    VECTOR_FEATURES = [
        HERO_STATE_DIM,
        STATION_DIM,
        CHARGER_DIM,
        NPC_DIM,
        LEGAL_ACT_DIM,
        INDICATOR_DIM,
        WAREHOUSE_DIM,
        MODE_DIM,
        TARGET_DIM,
    ]
    VECTOR_FEATURE_LEN = sum(VECTOR_FEATURES)
    FEATURE_SPLIT_SHAPE = VECTOR_FEATURES + [LOCAL_MAP_DIM]
    FEATURE_LEN = VECTOR_FEATURE_LEN + LOCAL_MAP_DIM
    DIM_OF_OBSERVATION = FEATURE_LEN

    # Action space / 动作空间
    ACTION_NUM = 8
    LABEL_SIZE_LIST = [ACTION_NUM]
    LEGAL_ACTION_SIZE_LIST = LABEL_SIZE_LIST.copy()

    # Value head (single) / 价值头（单头）
    VALUE_NUM = 1

    # PPO hyperparameters / PPO 超参数
    GAMMA = 0.995
    LAMDA = 0.95
    INIT_LEARNING_RATE_START = 0.0003
    # Entropy is already near max in current logs; keep exploration but reduce noise.
    BETA_START = 0.003
    CLIP_PARAM = 0.2
    VF_COEF = 0.5
    GRAD_CLIP_RANGE = 0.5
    USE_GRAD_CLIP = True

    # Goal-switching and reward shaping / 目标切换与奖励塑形
    SAFETY_MARGIN = 8.0

    DELIVERY_REWARD_SCALE = 2.5
    STEP_PENALTY = 0.002

    CHARGE_EVENT_REWARD = 0.20
    WAREHOUSE_REFILL_REWARD = 0.30
    WAREHOUSE_CHARGE_REWARD = 0.15

    PROGRESS_REWARD_STATION = 0.05
    PROGRESS_REWARD_CHARGER = 0.04
    PROGRESS_REWARD_WAREHOUSE_REFILL = 0.05
    PROGRESS_REWARD_WAREHOUSE_CHARGE = 0.03

    WAYPOINT_REACHED_REWARD = 0.04
    WAYPOINT_REPLAN_STUCK_STEPS = 3
    WAYPOINT_PROGRESS_TOL = 0.1
    WAYPOINT_LOOKAHEAD_RADIUS = 8
    WAYPOINT_GLOBAL_REPLAN_STUCK_COUNT = 1
    NO_MOVE_STUCK_STEPS = 2
    OSCILLATION_WINDOW = 6
    OSCILLATION_MIN_UNIQUE_POS = 3
    REVISIT_STUCK_COST = 0.4
    PATH_DEVIATION_REPLAN_DIST = 4
    WAYPOINT_MISSING_REPLAN_STEPS = 2

    GLOBAL_MAP_UNKNOWN = -1
    GLOBAL_MAP_FREE = 0
    GLOBAL_MAP_BLOCKED = 1
    GLOBAL_MAP_PRIOR_FREE = 2
    GLOBAL_MAP_UNKNOWN_COST = 1.5
    GLOBAL_MAP_FREE_COST = 1.0
    GLOBAL_MAP_PRIOR_FREE_COST = 1.2

    VISIT_COUNT_CAP = 10
    VISIT_PENALTY_SCALE = 0.01
    VISIT_GLOBAL_COST_WEIGHT = 0.3

    NPC_PENALTY_SCALE = 0.20
    NPC_PENALTY_RADIUS = 8
    NPC_ESCAPE_TRIGGER_DIST = 4
    NPC_ESCAPE_REWARD_SCALE = 0.02

    TERMINAL_COLLISION_PENALTY = -2.0
    TERMINAL_ENERGY_DEPLETED_PENALTY = -1.2

    NUMB_HEAD = 1
